[package]
name = "caddyfile-parser"
description = "A library for parsing and formatting Caddyfiles"
repository = "https://github.com/citadel-core/caddyfile-parser"
license = "MIT"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.63.0"
gobuild = "0.1.0-alpha.2"
